=> This is a combination of 4 commits. => This is the 1st commit message:
format-patch: format prettir Message-ID's

Change the Message-ID's from e.g.:

    $ git --no-pager format-patch --cover-letter --stdout HEAD~5.. | grep Message-Id
    Message-Id: <cover.1616506444.git.avarab@gmail.com>
    Message-Id: <5f308a89d8c37a186d58beff88542df00bc67975.1616506444.git.avarab@gmail.com>
    Message-Id: <23c781f1731bb77c16fb9c9a37e9d88f707af9bd.1616506444.git.avarab@gmail.com>
    Message-Id: <6d875d19fd7346f4a6dc47d2a1363db91e9643d5.1616506444.git.avarab@gmail.com>
    Message-Id: <98fe9e666fe4a595cf5396fd8d5c57b380c782b2.1616506444.git.avarab@gmail.com>
    Message-Id: <42efa1231aee85932058cc6d1571ab4ceb3e7eff.1616506444.git.avarab@gmail.com>
    Message-Id: <75555676ad3908b0f847a9ae154c35e12114c82f.1616506444.git.avarab@gmail.com>
    Message-Id: <142430338477d9d1bb25be66267225fb58498d92.1616506444.git.avarab@gmail.com>
    Message-Id: <bff81a3d39ed412e1b5be2cc570ab63ff6604810.1616506444.git.avarab@gmail.com>

To:

    $ git --no-pager format-patch --cover-letter --stdout HEAD~5.. | grep Message-Id
    Message-Id: <cover-0.9-00000000000-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-1.9-5f308a89d8c-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-2.9-23c781f1731-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-3.9-6d875d19fd7-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-4.9-98fe9e666fe-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-5.9-42efa1231ae-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-6.9-75555676ad3-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-7.9-14243033847-20210323T133337Z-avarab@gmail.com>
    Message-Id: <patch-8.9-bff81a3d39e-20210323T133337Z-avarab@gmail.com>

It also does the right thing when it comes to padding the patch number
there's >9 messages (or >99, >999, ...). E.g.:

    $ git --no-pager format-patch --cover-letter --stdout HEAD~10.. | grep -m2 Message-Id
    Message-Id: <cover-00.19-00000000000-20210323T133308Z-avarab@gmail.com>
    Message-Id: <patch-01.19-15ae82d5d6c-20210323T133308Z-avarab@gmail.com>

And when --cover-letter isn't specified:

    $ git --no-pager format-patch --stdout HEAD~2.. | grep -m2 Message-Id
    Message-Id: <patch-1.2-f157d3a5c2d-20210328T155559Z-avarab@gmail.com>
    Message-Id: <patch-2.2-a724c3ed353-20210328T155559Z-avarab@gmail.com>

Summary of things changed and to discuss:

 * We include the N/TOTAL position in the series, as noted above.

 * The ".git." part is gone, it didn't add any worthwhile signal. The
   main point of the Message-ID to be unique, sticking the MTA in there
   isn't needed. We've got --xmailer for that.

 * Let's use abbreviated OIDs, using null_oid as noted in a comment
   for the cover letter

 * Use ISO timestamp instead of Unix epoch. Make it easier to see at a
   glance how old a patch noted e.g. with a https://lore.kernel.org/git/
   discussion is.

 * We're still not using any funny-but-valid characters (as before) so
   e.g. gnome-terminal highlights this all as one thing to copy/paste.

Possible future improvements:

 * Should we spot e.g. a --subject-prefix="PATCH v2" and change the
   Message-ID to e.g. <cover-v2-$THE_REST> ?

 * I emit these patches into a git repo to keep track of notes/cover
   letter discussion. Sometimes I re-generate the patches and a smaller
   diff would be nicer. Could we safely omit the timestamp entirely?

   It would make this smaller, and presumably user.email+subject
   prefix+short OID would be unique enough.

This is the first in-tree user of the %zu format specifier, which is
in new in C99. For C89 we'd use %lu and a cast to "unsigned long", but
let's see if this works. It works on the compilers I've got access
to (clang, GCC on various archs, xlc & SunCC).

Signed-off-by: Ævar Arnfjörð Bjarmason <avarab@gmail.com>

=> This is the commit message #2:

format-patch: don't use %zu, use %lu and a cast

The Windows CI whines about it: https://github.com/avar/git/runs/2298653913

builtin/log.c: In function 'gen_message_id':
311
builtin/log.c:1047:29: error: unknown conversion type character 'z' in format [-Werror=format=]
312
 1047 |  strbuf_addf(&fmt, "%%s-%%0%zud.%%0%zud-%%s-%%s-%%s", tmp.len, tmp.len);
313
      |                             ^
314
builtin/log.c:1047:37: error: unknown conversion type character 'z' in format [-Werror=format=]
315
 1047 |  strbuf_addf(&fmt, "%%s-%%0%zud.%%0%zud-%%s-%%s-%%s", tmp.len, tmp.len);
316
      |                                     ^
317
builtin/log.c:1047:20: error: too many arguments for format [-Werror=format-extra-args]
318
 1047 |  strbuf_addf(&fmt, "%%s-%%0%zud.%%0%zud-%%s-%%s-%%s", tmp.len, tmp.len);
319
    CC builtin/ls-tree.o
320
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
321
    CC builtin/mailinfo.o

=> This is the commit message #3:

fix screwy totals with cover letters

I just hadn't noticed this, now:

    vm git (avar/format-patch-prettier-message-id $>) 0 $ ~/g/git/git format-patch --stdout HEAD~2..|grep ^Message
    Message-Id: <patch-1.2-958b0f66e7-20210409T082226Z-avarab@gmail.com>
    Message-Id: <patch-2.2-6f8ba890fc-20210409T082226Z-avarab@gmail.com>
    vm git (avar/format-patch-prettier-message-id $>) 0 $ ~/g/git/git format-patch --cover-letter --stdout HEAD~2..|grep ^Message
    Message-Id: <cover-0.2-0000000000-20210409T082231Z-avarab@gmail.com>
    Message-Id: <patch-1.2-958b0f66e7-20210409T082231Z-avarab@gmail.com>
    Message-Id: <patch-2.2-6f8ba890fc-20210409T082231Z-avarab@gmail.com>

Before:

    vm git (avar/format-patch-prettier-message-id $>) 0 $ git format-patch --cover-letter --stdout HEAD~2..|grep ^Message
    Message-Id: <cover-0.3-0000000000-20210409T082344Z-avarab@gmail.com>
    Message-Id: <patch-1.3-6f8ba890fc-20210409T082344Z-avarab@gmail.com>
    Message-Id: <patch-2.3-c6a79a2465-20210409T082344Z-avarab@gmail.com>
    vm git (avar/format-patch-prettier-message-id $>) 0 $ git format-patch --stdout HEAD~2..|grep ^Message
    Message-Id: <patch-1.2-6f8ba890fc-20210409T082347Z-avarab@gmail.com>
    Message-Id: <patch-2.2-c6a79a2465-20210409T082347Z-avarab@gmail.com>

=> This is  the commit message #4:

fixup conflict with master, use null_oid() as a function