notes/prune-packed/stash: use PARSE_OPT_ERROR_AT_NON_OPTION
Make use of the new PARSE_OPT_ERROR_AT_NON_OPTION in these three
commands. Unlike the cases changed in the preceding commits these
printed out custom error messages. This change changes them from e.g.:

    $ git notes prune blah
    error: too many arguments
    usage: git notes prune [<options>]
    [...]

To that "error" line being:

    error: unknown non-option: `blah'

I think this is more useful and consistent than just saying "too many
arguments", the "stash" case of saying that "clear" without arguments
is unimplemented is arguably making the error worse, but I think the
shorter code and consistency wins out even there.

Signed-off-by: Ævar Arnfjörð Bjarmason <avarab@gmail.com>